apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - image: monitoring:0.1
        name: monitoring
        imagePullPolicy: Never
        
